#/run/numberOfThreads 6
/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0

/gps/particle ion
/gps/ion 14 34 0
/gps/pos/type Point
/gps/pos/centre 0 0 -4000.2 mm
#/gps/ang/type beam1d
/gps/ang/type iso
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 -1 0
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 0.71 deg
/gps/energy 1870 MeV

#/run/printProgress 1
#/tracking/storeTrajectory 1
#/vis/scene/add/trajectories smooth
#/vis/scene/endOfEventAction accumulate 100
/run/beamOn 100